#yml基本语法：
#大小写敏感  使用缩进表示层级关系 缩进时不允许使用Tab键，只允许使用空格。
#缩进的空格数目不重要，只要相同层级的元素左侧对齐即可  #表示注释，从这个字符一直到行尾，都会被解析器忽略
#字符串默认不用引号，如果字符串中包含空格、特殊字符等，需要单引号；双引号不会对特殊字符转义

server: 
  port: 8001
  
mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.atguigu.springcloud.entities	# 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml 						# mapper映射文件

logging: 
  level: 
    com.atguigu.springcloud.dao: DEBUG						# 日志的方式打印和格式化sql

spring: 
   application: 
    name: microservicespringcloud-dept
   datasource: 
    type: com.alibaba.druid.pool.DruidDataSource			# 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver				# mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01				#  数据库名称
    username: root
    password: root
    dbcp2: 
      min-idle: 5											#  数据库连接池的最小维持连接数
      initial-size: 5										#  初始化连接数
      max-total: 5											#  最大连接数
      max-wait-millis: 200									#  等待连接获取的最大超时时间
      
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/            # 客户端注册进eureka服务列表内
  instance: 
      instance-id: microservicespringcloud-dept8001        # 自定义服务名称信息
      prefer-ip-address: true							   # 访问路径可以显示IP地址
      
info: 
  app.name: atguigu-microservicespringcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$